//$/r:LayoutMgr.dll
//$/r:SourceGrid.dll
//$/t:winexe
//& RunInOwnWindow

using System;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using LayoutManager;
using SourceGrid;

public class MainForm : Form
{
//Autogenerated
  private static void Main(string [] args)
  {
		Application.EnableVisualStyles();
   Application.SetCompatibleTextRenderingDefault(false);
   Application.ThreadException +=
   new System.Threading.ThreadExceptionEventHandler(ThreadException);
		try
   {
     Application.Run(new MainForm());
   }
   catch (Exception ex)
   {
     MessageBox.Show(ex.Message, "Error",
     MessageBoxButtons.OK, MessageBoxIcon.Error);
   }
	}   
  private static void ThreadException(
    object sender, System.Threading.ThreadExceptionEventArgs e)
    {
      MessageBox.Show(e.Exception.Message, "Error",
      MessageBoxButtons.OK, MessageBoxIcon.Error);
			 Application.Exit();
		 }        
//Autogenerated End

    Array data;
	int height;
	int width;
	private LayoutControl buttons;
	private LayoutControl widthControl;
	private LayoutControl heightControl;
	private LayoutControl window;
	TextBox heightBox;
	TextBox widthBox;
	Button create;
	Button process;
	Label widthLabel;
	Label heightLabel;
	ArrayGrid grid;
	public MainForm()
	{
		widthControl = new LayoutControl(new QLayout(QLayout.Direction.Vertical));
		heightControl = new LayoutControl(new QLayout(QLayout.Direction.Vertical));
		buttons = new LayoutControl(new QLayout(QLayout.Direction.Horizontal));
		window  = new LayoutControl(new RubberLayout());
		window.Dock = DockStyle.Fill;
		
		heightBox = new TextBox();
		widthBox = new TextBox();
		heightLabel = new Label();
		widthLabel = new Label();
		create = new Button();
		process = new Button();
		grid = new ArrayGrid();
		
		heightLabel.Text = "Высота";
		widthLabel.Text = "Ширина";
		create.Text = "Создать массив";
		process.Text = "Обработать";
		
        create.Click += buttonCreate;
        process.Click += buttonProcess;
        
		heightControl.Controls.AddRange(new Control[]{heightLabel,heightBox});
		widthControl.Controls.AddRange(new Control[]{widthLabel,widthBox});
		buttons.Controls.AddRange(new Control[]{heightControl,widthControl,create,process});
		buttons.Bounds = new Rectangle(0,0,400,40);
		grid.Bounds = new Rectangle(0,40,400,160);
		window.Size = new Size (400,200);
		window.Controls.AddRange(new Control[]{buttons,grid});
        Controls.Add(window);
	  }
    void buttonCreate (Object sender, EventArgs e) 
		{
			   var converted = false;
					try {
          height = int.Parse(heightBox.Text);
          width = int.Parse(widthBox.Text);
					  converted = true;
				  } catch {}
					if (converted)
					{
            data = Array.CreateInstance(typeof(float), height, width);
            grid.DataSource = data;
            grid.Size = new Size(400,160);
            for (int i = 0; i < width; i++)
            {
                grid.Columns.Add(new ColumnInfo(grid));
            }
				  }
    }
    void buttonProcess (Object sender, EventArgs e) 
		{
			   if (data!=null)
				 {
            if (isSymmetric()) {
                MessageBox.Show(getSum().ToString());
            }
            grid.Refresh();
				 }
    }

	public float getSum() 
	{
      float sum = 0;
      for (int i=0;i<width;++i)
      {
        int j=0;
        for (;j<i;++j)
        {
          sum+=(float)data.GetValue(i,j);
        }
        ++j;
        for (;j<height;++j)
        {
          data.SetValue(0,i,j);
        }
      }
      return sum;
	}
	public bool isSymmetric()
	{
		 bool res = true;
		 for (int i=0;i<width;++i)
		 {
			 for (int j=0;j<i;++j)
			 {
				 if ((float)data.GetValue(i,j)!=(float)data.GetValue(j,i)) {
                    res=false;
                    break;
				 }
			 }
			 if (res==false)
			 {
				  break;
			 }
		 }
		 return res;
	}
}