//$/r:Matrix.dll
//$/r:LayoutMgr.dll
//$/r:SourceGrid.dll
//$/t:winexe
//& RunInOwnWindow

using System;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using LayoutManager;
using SourceGrid;

public class MainForm : Form
{
    MainMenu menu;
    MenuItem settingsMenu;
    MenuItem aboutMenu;
    MenuItem newMenu;
    MenuItem closeMenu;
    MenuItem windowMenu;
    MenuItem matrixMenu;
    public static bool mode = true;
    public static int counter = 0;
    public MainForm()
    {
        Text = "Программа 7";
        IsMdiContainer = true;
        menu = new MainMenu();
        Menu = menu;
        settingsMenu = new MenuItem("&Настройки");
        aboutMenu = new MenuItem("&О программе");
        newMenu = new MenuItem("&Новая");
        closeMenu = new MenuItem("&Закрыть");
        windowMenu = new MenuItem("&Список");
        matrixMenu = new MenuItem("&Матрицы");
        matrixMenu.MenuItems.Add(newMenu);
        matrixMenu.MenuItems.Add(newMenu);
        matrixMenu.MenuItems.Add(closeMenu);
        matrixMenu.MenuItems.Add(windowMenu);
        menu.MenuItems.Add(matrixMenu);
        menu.MenuItems.Add(settingsMenu);
        menu.MenuItems.Add(aboutMenu);
        windowMenu.MdiList = true;
        settingsMenu.Click+= delegate(Object sender, EventArgs e)
        {
            var s = new SettingsForm();
            s.Text = "Настройки";
            s.Show();
        };
        aboutMenu.Click+= delegate(Object sender, EventArgs e)
        {
            var a = new Form();
            a.Text = "О программе";
            a.Size = new Size(200,60);
            var l = new Label();
            l.Size = new Size(200,40);
            l.Text = "Программа обработки матриц";
            a.Controls.Add(l);
            a.Show();
        };
        newMenu.Click+= delegate(Object sender, EventArgs e)
        {
            var childForm = new ChildForm();
            childForm.MdiParent = this;
            childForm.Show();
        };
        closeMenu.Click+=delegate(Object sender, EventArgs e)
        {
            var activeChild = this.ActiveMdiChild;
            if (activeChild!=null)
            {
                activeChild.Close();
            }
        };
    }
    //Autogenerated
  private static void Main(string [] args)
  {
   Application.EnableVisualStyles();
   Application.SetCompatibleTextRenderingDefault(false);
   Application.ThreadException +=
   new System.Threading.ThreadExceptionEventHandler(ThreadException);
		try
   {
     Application.Run(new MainForm());
   }
   catch (Exception ex)
   {
     MessageBox.Show(ex.Message, "Error",
     MessageBoxButtons.OK, MessageBoxIcon.Error);
   }
	}   
  private static void ThreadException(
    object sender, System.Threading.ThreadExceptionEventArgs e)
    {
      MessageBox.Show(e.Exception.Message, "Error",
      MessageBoxButtons.OK, MessageBoxIcon.Error);
			 Application.Exit();
		 }        
//Autogenerated End
}

public class ChildForm : Form
{
	Matrix data;
	private LayoutControl buttons;
	private LayoutControl widthControl;
	private LayoutControl heightControl;
	private LayoutControl window;
	TextBox heightBox;
	TextBox widthBox;
	Button create;
	Button process;
	Label widthLabel;
	Label heightLabel;
	ArrayGrid grid;
	public ChildForm()
	{
        MainForm.counter++;
        Text = "Матрица " + MainForm.counter.ToString();
		widthControl = new LayoutControl(new QLayout(QLayout.Direction.Vertical));
		heightControl = new LayoutControl(new QLayout(QLayout.Direction.Vertical));
		buttons = new LayoutControl(new QLayout(QLayout.Direction.Horizontal));
		window  = new LayoutControl(new RubberLayout());
		window.Dock = DockStyle.Fill;
		
		heightBox = new TextBox();
		widthBox = new TextBox();
		heightLabel = new Label();
		widthLabel = new Label();
		create = new Button();
		process = new Button();
		grid = new ArrayGrid();
		
		heightLabel.Text = "Высота";
		widthLabel.Text = "Ширина";
		create.Text = "Создать массив";
		process.Text = "Обработать";
		
		create.Click += buttonCreate;
		process.Click += buttonProcess;
        
		heightControl.Controls.AddRange(new Control[]{heightLabel,heightBox});
		widthControl.Controls.AddRange(new Control[]{widthLabel,widthBox});
		buttons.Controls.AddRange(new Control[]{heightControl,widthControl,create,process});
		buttons.Bounds = new Rectangle(0,0,440,40);
		grid.Bounds = new Rectangle(0,40,440,160);
		window.Size = new Size (440,200);
      Size = new Size (340,240);
		window.Controls.AddRange(new Control[]{buttons,grid});
		Controls.Add(window);
	}

	void buttonCreate (Object sender, EventArgs e) 
	{
		var converted = false;
		int height = 1, width = 1;
		try {
			height = int.Parse(heightBox.Text);
			width = int.Parse(widthBox.Text);
			converted = true;
		} catch {}
		if (converted)
		{
			data = new Matrix(height,width);
			grid.DataSource = data.data;
			grid.Size = new Size(400,160);
            grid.Columns.Clear();
			for (int i = 0; i < width; i++)
			{
				grid.Columns.Add(new ColumnInfo(grid));
			}
		}
	}
	void buttonProcess (Object sender, EventArgs e) 
	{
		if (data!=null)
		{
          if (MainForm.mode)
          {
              var row = data.FindOddEven();
              MessageBox.Show("Чётных: "+row.even+"\nНечётных: "+row.odd,"Типов элементов");
          }
          else
          {
              var r = new ResultForm(data.FindSubzeroes());
             r.Show();
          }
		}
	}
}

public class SettingsForm : Form
{
    RadioButton findOddEvenRB;
    RadioButton findSubzeroesRB;
    LayoutControl window;

    public SettingsForm()
    {   
        window =  new LayoutControl(new QLayout(QLayout.Direction.Vertical));
        
        findOddEvenRB = new RadioButton();
        findSubzeroesRB = new RadioButton();
        
        if (MainForm.mode) 
        {
            findOddEvenRB.Checked = true;
        }
        else
        {
            findSubzeroesRB.Checked = true;
        }
        findOddEvenRB.Text = "Найти кол-во чётных и нечётных элементов";
        findSubzeroesRB.Text = "Найти первые отрицательные элементы";
        
        Size = new Size (300,90);
        window.Dock = DockStyle.Fill;
        window.Controls.AddRange(new Control[]{findOddEvenRB,findSubzeroesRB});        
        Controls.Add(window);
        FormClosing+=SFClosing;
    }
    public void SFClosing(Object sender, FormClosingEventArgs e)
    {
        if (findOddEvenRB.Checked)
        {
            MainForm.mode = true;
        }
        else
        {
            MainForm.mode = false;
        }
    }
}

public class ResultForm : Form
{
    public static float[,] data;
    private LayoutControl window;
    ArrayGrid grid;
    public ResultForm(float[,] d)
    {
        Text = "Первые отрицательные элементы";
        data = d;
        grid = new ArrayGrid();
        grid.DataSource = data;
        grid.Columns.Clear();
        for (int i = 0; i < data.Length; i++)
			{
				grid.Columns.Add(new ColumnInfo(grid));
			}
        MinimumSize = new Size(200,60);
        Size = new Size(200,60);
        window  = new LayoutControl(new RubberLayout());
        window.Dock = DockStyle.Fill;
        window.Controls.Add(grid);
        Controls.Add(grid);
    }
}