//$/r:Matrix.dll
//$/r:LayoutMgr.dll
//$/r:SourceGrid.dll
//$/t:winexe
//& RunInOwnWindow

using System;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using LayoutManager;
using SourceGrid;

public class MainForm : Form
{
//Autogenerated
  private static void Main(string [] args)
  {
		Application.EnableVisualStyles();
   Application.SetCompatibleTextRenderingDefault(false);
   Application.ThreadException +=
   new System.Threading.ThreadExceptionEventHandler(ThreadException);
		try
   {
     Application.Run(new MainForm());
   }
   catch (Exception ex)
   {
     MessageBox.Show(ex.Message, "Error",
     MessageBoxButtons.OK, MessageBoxIcon.Error);
   }
	}   
  private static void ThreadException(
    object sender, System.Threading.ThreadExceptionEventArgs e)
    {
      MessageBox.Show(e.Exception.Message, "Error",
      MessageBoxButtons.OK, MessageBoxIcon.Error);
			 Application.Exit();
		 }        
//Autogenerated End

	Matrix data;
	private LayoutControl buttons;
	private LayoutControl widthControl;
	private LayoutControl heightControl;
	private LayoutControl window;
	TextBox heightBox;
	TextBox widthBox;
	Button create;
	Button process;
	Label widthLabel;
	Label heightLabel;
	ArrayGrid grid;
	public MainForm()
	{
		widthControl = new LayoutControl(new QLayout(QLayout.Direction.Vertical));
		heightControl = new LayoutControl(new QLayout(QLayout.Direction.Vertical));
		buttons = new LayoutControl(new QLayout(QLayout.Direction.Horizontal));
		window  = new LayoutControl(new RubberLayout());
		window.Dock = DockStyle.Fill;
		
		heightBox = new TextBox();
		widthBox = new TextBox();
		heightLabel = new Label();
		widthLabel = new Label();
		create = new Button();
		process = new Button();
		grid = new ArrayGrid();
		
		heightLabel.Text = "Высота";
		widthLabel.Text = "Ширина";
		create.Text = "Создать массив";
		process.Text = "Обработать";
		
		create.Click += buttonCreate;
		process.Click += buttonProcess;
        
		heightControl.Controls.AddRange(new Control[]{heightLabel,heightBox});
		widthControl.Controls.AddRange(new Control[]{widthLabel,widthBox});
		buttons.Controls.AddRange(new Control[]{heightControl,widthControl,create,process});
		buttons.Bounds = new Rectangle(0,0,400,40);
		grid.Bounds = new Rectangle(0,40,400,160);
		window.Size = new Size (400,200);
		window.Controls.AddRange(new Control[]{buttons,grid});
		Controls.Add(window);
	}
	void buttonCreate (Object sender, EventArgs e) 
	{
		var converted = false;
		int height = 1, width = 1;
		try {
			height = int.Parse(heightBox.Text);
			width = int.Parse(widthBox.Text);
			converted = true;
		} catch {}
		if (converted)
		{
			data = new Matrix(height,width);
			grid.DataSource = data.data;
			grid.Size = new Size(400,160);
            grid.Columns.Clear();
			for (int i = 0; i < width; i++)
			{
				grid.Columns.Add(new ColumnInfo(grid));
			}
		}
	}
	void buttonProcess (Object sender, EventArgs e) 
	{
		if (data!=null)
		{
			data.moveToEnd();
			grid.DataSource = data.data;
			grid.Columns.Clear();
			for (int i = 0; i < data.width; i++)
			{
				grid.Columns.Add(new ColumnInfo(grid));
			}
			grid.Update();
		}
	}
}