//$/r:Matrix.dll
//$/r:LayoutMgr.dll
//$/r:SourceGrid.dll
//$/t:winexe
//& RunInOwnWindow

using System;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using LayoutManager;
using SourceGrid;

public class MainForm : Form
{
//Autogenerated
  private static void Main(string [] args)
  {
   Application.EnableVisualStyles();
   Application.SetCompatibleTextRenderingDefault(false);
   Application.ThreadException +=
   new System.Threading.ThreadExceptionEventHandler(ThreadException);
		try
   {
     Application.Run(new MainForm());
   }
   catch (Exception ex)
   {
     MessageBox.Show(ex.Message, "Error",
     MessageBoxButtons.OK, MessageBoxIcon.Error);
   }
	}   
  private static void ThreadException(
    object sender, System.Threading.ThreadExceptionEventArgs e)
    {
      MessageBox.Show(e.Exception.Message, "Error",
      MessageBoxButtons.OK, MessageBoxIcon.Error);
			 Application.Exit();
		 }        
//Autogenerated End

	Matrix data;
	private LayoutControl buttons;
	private LayoutControl widthControl;
	private LayoutControl heightControl;
	private LayoutControl window;
	TextBox heightBox;
	TextBox widthBox;
	Button create;
	Button process;
	Label widthLabel;
	Label heightLabel;
	ArrayGrid grid;
    MainMenu menu;
    MenuItem settingsMenu;
    MenuItem aboutMenu;
    public static float minimum = 1.0F;
    public static float maximum = 3.0F;
    public static bool mode = true;
	public MainForm()
	{
      Text = "Программа 6";
		widthControl = new LayoutControl(new QLayout(QLayout.Direction.Vertical));
		heightControl = new LayoutControl(new QLayout(QLayout.Direction.Vertical));
		buttons = new LayoutControl(new QLayout(QLayout.Direction.Horizontal));
		window  = new LayoutControl(new RubberLayout());
		window.Dock = DockStyle.Fill;
		
		heightBox = new TextBox();
		widthBox = new TextBox();
		heightLabel = new Label();
		widthLabel = new Label();
		create = new Button();
		process = new Button();
		grid = new ArrayGrid();
		
		heightLabel.Text = "Высота";
		widthLabel.Text = "Ширина";
		create.Text = "Создать массив";
		process.Text = "Обработать";
		
		create.Click += buttonCreate;
		process.Click += buttonProcess;
        
		heightControl.Controls.AddRange(new Control[]{heightLabel,heightBox});
		widthControl.Controls.AddRange(new Control[]{widthLabel,widthBox});
		buttons.Controls.AddRange(new Control[]{heightControl,widthControl,create,process});
		buttons.Bounds = new Rectangle(0,0,440,40);
		grid.Bounds = new Rectangle(0,40,440,160);
		window.Size = new Size (440,200);
      Size = new Size (340,240);
		window.Controls.AddRange(new Control[]{buttons,grid});
		Controls.Add(window);
        menu = new MainMenu();
        Menu = menu;
        settingsMenu = new MenuItem("&Настройки");
        aboutMenu = new MenuItem("&О программе");
        menu.MenuItems.Add(settingsMenu);
        menu.MenuItems.Add(aboutMenu);
        settingsMenu.Click+= delegate(Object sender, EventArgs e)
        {
            var s = new SettingsForm();
            s.Text = "Настройки";
            s.Show();
        };
        aboutMenu.Click+= delegate(Object sender, EventArgs e)
        {
            var a = new Form();
            a.Text = "О программе";
            a.Size = new Size(200,60);
            var l = new Label();
            l.Size = new Size(200,40);
            l.Text = "Программа обработки матриц";
            a.Controls.Add(l);
            a.Show();
        };
	}

	void buttonCreate (Object sender, EventArgs e) 
	{
		var converted = false;
		int height = 1, width = 1;
		try {
			height = int.Parse(heightBox.Text);
			width = int.Parse(widthBox.Text);
			converted = true;
		} catch {}
		if (converted)
		{
			data = new Matrix(height,width);
			grid.DataSource = data.data;
			grid.Size = new Size(400,160);
            grid.Columns.Clear();
			for (int i = 0; i < width; i++)
			{
				grid.Columns.Add(new ColumnInfo(grid));
			}
		}
	}
	void buttonProcess (Object sender, EventArgs e) 
	{
		if (data!=null)
		{
          if (mode)
          {
              var row = data.findMinCount(minimum,maximum);
              MessageBox.Show("Номер ряда: "+row.ToString(),"Минимальное кол-во элементов в интервале");
          }
          else
          {
              var r = new ResultForm(data.FindMaximums());
              r.Show();
          }
		}
	}
}

public class SettingsForm : Form
{
    RadioButton findMinCountRB;
    RadioButton findMaximumsRB;
    TextBox minimumTB;
    TextBox maximumTB;
    Label minimumL;
    Label maximumL;
    LayoutControl window;
    LayoutControl tbControl;
    LayoutControl minimumControl;
    LayoutControl maximumControl;
    public SettingsForm()
    {   
        window =  new LayoutControl(new QLayout(QLayout.Direction.Vertical));
        tbControl =  new LayoutControl(new QLayout(QLayout.Direction.Horizontal));
        minimumControl =  new LayoutControl(new QLayout(QLayout.Direction.Vertical));
        maximumControl =  new LayoutControl(new QLayout(QLayout.Direction.Vertical));
        
        findMinCountRB = new RadioButton();
        findMaximumsRB = new RadioButton();
        minimumL = new Label();
        maximumL = new Label();
        minimumTB = new TextBox();
        maximumTB = new TextBox();
        
        if (MainForm.mode) 
        {
            findMinCountRB.Checked = true;
        }
        else
        {
            findMaximumsRB.Checked = true;
        }
        findMinCountRB.Text = "Найти элементы в интервале";
        findMaximumsRB.Text = "Найти максимальные элементы";
        minimumL.Text = "Минимум";
        maximumL.Text = "Максимум";
        minimumTB.Text = MainForm.minimum.ToString();
        maximumTB.Text = MainForm.maximum.ToString();

        Size = new Size (300,160);
        window.Dock = DockStyle.Fill;
        minimumControl.Controls.AddRange(new Control[]{minimumL,minimumTB});
        maximumControl.Controls.AddRange(new Control[]{maximumL,maximumTB});
        tbControl.Controls.AddRange(new Control[]{minimumControl,maximumControl});
        window.Controls.AddRange(new Control[]{findMinCountRB,findMaximumsRB,tbControl});        
        Controls.Add(window);
        FormClosing+=SFClosing;
    }
    public void SFClosing(Object sender, FormClosingEventArgs e)
    {
        try {
            MainForm.minimum = float.Parse(minimumTB.Text);
            MainForm.maximum = float.Parse(maximumTB.Text);
            if (MainForm.maximum < MainForm.minimum)
            {
                var temp = MainForm.maximum;
                MainForm.maximum = MainForm.minimum;
                MainForm.minimum = temp;
            }
        } catch {}
        if (findMinCountRB.Checked)
        {
            MainForm.mode = true;
        }
        else
        {
            MainForm.mode = false;
        }
    }
}

public class ResultForm : Form
{
    public static float[,] data;
    private LayoutControl window;
    ArrayGrid grid;
    public ResultForm(float[,] d)
    {
        Text = "Максимумы";
        data = d;
        grid = new ArrayGrid();
        grid.DataSource = data;
        grid.Columns.Clear();
        grid.Columns.Add(new ColumnInfo(grid));
        MinimumSize = new Size(50,160);
        Size = new Size(50,160);
        window  = new LayoutControl(new RubberLayout());
        window.Dock = DockStyle.Fill;
        window.Controls.Add(grid);
        Controls.Add(grid);
    }
}